dictionaries = ["en_us"]
words = [
  "aborter",
  "accessors",
  "affordance",
  "backend's",
  "bunx",
  "bytea",
  "cjk",
  "collab",
  "cooldown",
  "corvu",
  "cpuprofile",
  "dedup",
  "dedupe",
  "dialog's",
  "dialogs",
  "dragover",
  "dropzone",
  "elysia",
  "elysia's",
  "elysiajs",
  "frontend's",
  "gunzip",
  "hocuspocus",
  "hsl",
  "kobalte",
  "loadend",
  "lookups",
  "microtasks",
  "minmax",
  "mousemove",
  "mouseup",
  "mql",
  "nanotar",
  "nord",
  "nosniff",
  "nums",
  "oklch",
  "oxlint",
  "pagebreak",
  "proj",
  "punct",
  "readwrite",
  "refetches",
  "replit",
  "shiki",
  "shiki's",
  "solidjs",
  "somoto",
  "strikethrough",
  "tinymist",
  "typebox",
  "typs",
  "typst's",
  "typstogether",
  "uiw",
  "uiw's",
  "upgradeneeded",
  "uppercased",
  "upserts",
  "vedivad",
  "vscode",
  "whatever's",
  "xlink",
  "vfs",
  "ydoc",
  "yjs",
]
include_paths = ["**/*.md", "**/*.ts", "**/*.tsx"]
ignore_paths = ["**/components/ui/**", "frontend/src/routes/project/editor-actions.test.ts"]
use_global = false
