dictionaries = ["en_us"]
words = [
  "bunx",
  "bytea",
  "collab",
  "crossws",
  "elysia",
  "elysiajs",
  "hocuspocus",
  "logomark",
  "ost",
  "savepoints",
  "solidjs",
  "typebox",
  "typstogether",
  "upserts",
  "ypst",
]
include_paths = ["**/*.md", "**/*.ts", "**/*.tsx"]
use_global = false
