dictionaries = ["en_us"]
words = [
  "aborter",
  "accessors",
  "bunx",
  "bytea",
  "collab",
  "cva",
  "elysia",
  "elysiajs",
  "hocuspocus",
  "minmax",
  "ost",
  "proj",
  "savepoints",
  "solidjs",
  "somoto",
  "typebox",
  "typs",
  "typstogether",
  "uiw",
  "upserts",
  "vedivad",
  "vfs",
  "wss",
  "ydoc",
  "yjs",
  "ypst",
  "ytext",
]
include_paths = [
  "**/*.md",
  "**/*.ts",
  "**/*.tsx",
]
ignore_paths = ["**/components/ui/**"]
use_global = false
