telemetry = false

[install]
# Package should be at least a week old to prevent supply chain vulnerabilities
minimumReleaseAge = 0 # 3600 × 24 × 7 = 604800

[test]
preload = ["./backend/test/setup.ts"]
coveragePathIgnorePatterns = ["**/test/**", "**/*.test.ts", "frontend/src/components/**"]
