name: CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install typstyle
        uses: taiki-e/install-action@v2
        with:
          tool: codebook-lsp

      - name: Check Formatting
        run: codebook-lsp lint .

  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

  lint:
    runs-on: ubuntu-latest
    name: Lint
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint & Formatting check
        run: bun lint

      - name: Type check
        run: bun check

      - name: Install typstyle
        uses: taiki-e/install-action@v2
        with:
          tool: typstyle

      - name: Check Formatting of typst files
        run: typstyle --line-width 80 --wrap-text --check .

  test:
    runs-on: ubuntu-latest
    name: Test
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Test
        run: bun test
